common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name = 'common/login.html'),
         name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

# from pybo import views -> include를 사용함으로써 필요가 없게 됨
urlpatterns = [
    path("admin/", admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name = 'index')
]

pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views, vote_views, comment_question_views, comment_answer_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/decision/<int:question_id>/', question_views.question_decision, name='question_decision'),
    path('question/question_detail/<int:question_id>/', question_views.question_detail, name='question_detail'),
    path('question/approval/<int:question_id>/', question_views.question_ocra, name='question_ocra'),
    path('open_question_modal/<int:question_id>/',question_views.open_question_modal, name='open_question_modal'),
    path('determine_qc/', question_views.determine_qc, name='determine_qc'),
    path('open_question_modal/', question_views.open_question_modal, name='open_question_modal'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    # comment_question_views.py
    path('comment/create/question/<int:question_id>/', comment_question_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_question_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_question_views.comment_delete_question, name='comment_delete_question'),

    # comment_answer_views.py
    path('comment/create/answer/<int:answer_id>/', comment_answer_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_answer_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_answer_views.comment_delete_answer, name='comment_delete_answer'),

    # vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
    path('vote/comment/question/<int:comment_id>/', vote_views.vote_comment_question, name='vote_comment_question'),
    path('vote/comment/answer/<int:comment_id>/', vote_views.vote_comment_answer, name='vote_comment_answer'),
]

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")
    position = forms.CharField(max_length = 200)
    symmetric_key = forms.CharField(max_length=128, required=False)
    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email", "position",'symmetric_key')

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from .forms import UserForm
import secrets
from django.core.mail import EmailMessage
from django.template.loader import render_to_string

def generate_symmetric_key(key_length=16):
    key = secrets.token_hex(key_length)
    return key

pos = {"외부인" : 0, "사원" : 1, "대리" : 2, "과장" : 3, "차장": 4, "부장": 5, "짱" : 10000}


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            position = request.POST.get("position")
            user = form.save(commit=False)

            if position in pos:
                user.last_name = pos[position]
            else:
                user.last_name = pos["외부인"]

            # 공개 키 생성 및 설정
            symmetric_key = generate_symmetric_key()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')

            # user.first_name = symmetric_key
            user.first_name = f"{symmetric_key} {raw_password}"
            subject = "대칭키 공유"  # 타이틀
            to = [user.email]  # 수신할 이메일 주소
            from_email = "qudrb24@naver.com"  # 발신할 이메일 주소
            message = symmetric_key

            email = EmailMessage()
            email.subject = subject
            email.body = f"{user.username}님의 대칭키 : {message}"
            email.from_email = from_email
            email.to = to
            email.send()



            user.save()
            user = authenticate(username = username, password = raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserForm()
    return render(request, "common/signup.html", { 'form' : form })

templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span><a href="{% url 'common:signup' %}">회원가입</a></span>
        </div>
    </div>
    <br>
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <br>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <br>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

templates/common/login_otp.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:signup' %}">계정을 만드세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사번</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
            <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>계정생성</h4>
        </div>
        <div class="col-8 text-right">
            <span><a href="{% url 'common:login' %}">로그인</a></span>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">ID</label>
            <input type="text" class="form-control" name="username" id="username" placeholder="ID를 입력하세요"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1" placeholder="8자 이상을 입력하세요"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2" placeholder="8자 이상을 입력하세요"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email" placeholder="email을 입력하세요"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="position">직급</label>
            <input type="text" class="form-control" name="position" id="position" placeholder="사원 / 대리 / 과장 / 차장 / 부장"
                   value="{{ form.position.value|default_if_none:'' }}">
        </div>
        <br>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}