common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name = 'common/login.html'),
         name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

# from pybo import views -> include를 사용함으로써 필요가 없게 됨
urlpatterns = [
    path("admin/", admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name = 'index')
]

pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views, vote_views, comment_question_views, comment_answer_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/decision/<int:question_id>/', question_views.question_decision, name='question_decision'),
    path('question/question_detail/<int:question_id>/', question_views.question_detail, name='question_detail'),
    path('question/approval/<int:question_id>/', question_views.question_ocra, name='question_ocra'),
    path('open_question_modal/<int:question_id>/',question_views.open_question_modal, name='open_question_modal'),
    path('determine_qc/', question_views.determine_qc, name='determine_qc'),
    path('open_question_modal/', question_views.open_question_modal, name='open_question_modal'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    # comment_question_views.py
    path('comment/create/question/<int:question_id>/', comment_question_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_question_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_question_views.comment_delete_question, name='comment_delete_question'),

    # comment_answer_views.py
    path('comment/create/answer/<int:answer_id>/', comment_answer_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_answer_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_answer_views.comment_delete_answer, name='comment_delete_answer'),

    # vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
    path('vote/comment/question/<int:comment_id>/', vote_views.vote_comment_question, name='vote_comment_question'),
    path('vote/comment/answer/<int:comment_id>/', vote_views.vote_comment_answer, name='vote_comment_answer'),
]

pybo/views/base_views.py
import logging

from django.core.paginator import Paginator
from django.db.models import Q, Count
from django.shortcuts import render, get_object_or_404

from ..models import Question, Comment

logger = logging.getLogger('pybo')


def index(request):
    logger.info("INFO 레벨로 출력")
    # 입력 params
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    so = request.GET.get('so', 'recent')  # 정렬기준

    # 정렬
    if so == 'pending':
        question_list = Question.objects.filter(status='pending').order_by('-create_date')
    elif so == 'approved':
        question_list = Question.objects.filter(status='approved').order_by('-create_date')
    elif so == 'rejected':
        question_list = Question.objects.filter(status='rejected').order_by('-create_date')
    elif so == 'on_hold':
        question_list = Question.objects.filter(status='holding').order_by('-create_date')
    else:  # recent
        question_list = Question.objects.order_by('-create_date')


    # 검색
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목검색
            Q(content__icontains=kw) |  # 내용검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이검색
            Q(answer__author__username__icontains=kw) |# 답변 글쓴이검색
            Q(question_hash__icontains=kw) # 해시값 검색
        ).distinct()

    # 페이징처리
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'so': so}  # <------ so 추가
    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    """
    pybo 내용 출력
    """
    # 질문 댓글 pagination 해야함.
    page = request.GET.get('page', '1')
    question = get_object_or_404(Question, pk=question_id)
    so = request.GET.get('so', 'recent')  # 정렬기준
    basic_comment_list = Comment.objects.filter(question = question)

    # 정렬

    if so == 'pending':
        comment_list = basic_comment_list.filter(status='pending').order_by('-create_date')
    elif so == 'approved':
        comment_list = basic_comment_list.filter(status='approved').order_by('-create_date')
    elif so == 'rejected':
        comment_list = basic_comment_list.filter(status='rejected').order_by('-create_date')
    elif so == 'holding':
        comment_list = basic_comment_list.filter(status='holding').order_by('-create_date')
    else:  # recent
        comment_list = basic_comment_list.order_by('-create_date')

    paginator = Paginator(comment_list, 10)
    page_obj = paginator.get_page(page)
    context = {'question': question, 'comment_list' : page_obj, 'page' : page, 'so' : so}

    return render(request, 'pybo/question_detail.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <!-- 부트스트랩 CSS -->

    <!--  모달   ----------->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

    <!-- jQuery 및 Popper.js -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>

    <!-- 부트스트랩 JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

    <!--  모달   ----------->

    <title>결재시스템</title>
</head>
<body>
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'pybo:index' %}">Approval System</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>